CREATE DATABASE [OLTP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OLTP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\OLTP.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OLTP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\OLTP_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
ALTER DATABASE [OLTP] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [OLTP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OLTP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OLTP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OLTP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OLTP] SET ARITHABORT OFF 
GO
ALTER DATABASE [OLTP] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [OLTP] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OLTP] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [OLTP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OLTP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OLTP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OLTP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OLTP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OLTP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OLTP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OLTP] SET  DISABLE_BROKER 
GO
ALTER DATABASE [OLTP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OLTP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OLTP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OLTP] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OLTP] SET  READ_WRITE 
GO
ALTER DATABASE [OLTP] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [OLTP] SET  MULTI_USER 
GO
ALTER DATABASE [OLTP] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OLTP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [OLTP] SET DELAYED_DURABILITY = DISABLED 
GO
USE [OLTP]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [OLTP]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [OLTP] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
