USE OLTP
GO

-- CHECK 3NF
SELECT *
FROM Customers
-- 3NF CONFIRMED

SELECT *
FROM Transactions

-- TRANSITIVE DEPENDENCIES NEED TO BE SEPARATED INTO THEIR OWN TABLE
SELECT item, [description], retail_price
INTO TMP
FROM Transactions
--3455

SELECT *
FROM TMP

--MAKE THE NEW TABLE 1NF - REMOVE DUPLICATES
SELECT DISTINCT *
INTO Items
FROM TMP
-- 126

-- CHECK
SELECT *
FROM Items
-- 3NF CONFIRMED

-- NOW WE REMOVE THE EXTRACTED ROWS FROM THE TRANSACTIONS TABLE
-- BUT KEEP THE FOREIGN KEY "ITEM"
ALTER TABLE Transactions
DROP COLUMN [description], retail_price

SELECT * FROM Transactions
-- 3NF CONFIRMED

DROP TABLE TMP
